'use strict';
let profile, published, previewTimer;
const DRAFT='jamal-profile-draft-v2', history=[], assets={}, assetURLs={};
const $=id=>document.getElementById(id);
const form=$('editor-form'), status=$('editor-status'), frame=$('preview-frame');
const titles={identity:'Introduction & links',experience:'Work experience',projects:'Projects & portfolio',education:'Education',skills:'Skills & methods',elsewhere:'Other links',highlights:'Evidence & highlights',contact:'Contact message'};
const labelNames={cv:'CV file path',photo:'Photo file path',intro:'Introduction',current:'Current role',fields:'Subjects & sectors',points:'Experience bullets',methods:'Methods & tools',status:'Project status or year',url:'Link URL'};
const templates={experience:{role:'New role',organization:'',dates:'',fields:'',points:['']},projects:{title:'New project',category:'',description:'',methods:'',status:'',links:[]},education:{degree:'',institution:'',year:''},skills:{area:'',detail:''},elsewhere:{title:'',description:'',url:'https://'},links:{label:'',url:'https://'}};
const identityKeys=['name','headline','intro','current','photo','cv','email','linkedin','github','research'];
const label=k=>labelNames[k]||k.replace(/_/g,' ').replace(/^./,s=>s.toUpperCase());
const message=text=>status.textContent=text;
function get(path){return path.reduce((v,k)=>v[k],profile);}
function checkpoint(){history.push(JSON.stringify(profile));if(history.length>50)history.shift();$('undo-button').disabled=false;}
function set(path,value){let v=profile;path.slice(0,-1).forEach(k=>v=v[k]);v[path.at(-1)]=value;save();}
function save(){try{localStorage.setItem(DRAFT,JSON.stringify(profile));message('Draft saved in this browser. Download and upload to GitHub to publish.');}catch(e){message('Browser storage unavailable. Download your changes before leaving this page.');}clearTimeout(previewTimer);previewTimer=setTimeout(sendPreview,150);}
function validProfile(d){
 const strings=(o,keys)=>o&&typeof o==='object'&&keys.every(k=>typeof o[k]==='string');
 if(!strings(d,[...identityKeys,'contact']))return false;
 if(!Array.isArray(d.highlights)||!d.highlights.every(x=>typeof x==='string'))return false;
 return Object.entries(templates).filter(([k])=>k!=='links').every(([k,t])=>Array.isArray(d[k])&&d[k].every(x=>strings(x,Object.keys(t).filter(p=>!Array.isArray(t[p])))&&(k!=='experience'||Array.isArray(x.points)&&x.points.every(p=>typeof p==='string'))&&(k!=='projects'||Array.isArray(x.links)&&x.links.every(l=>strings(l,['label','url'])))));
}
function button(text,fn,cls='secondary'){const b=document.createElement('button');b.type='button';b.textContent=text;b.className=cls;b.onclick=fn;return b;}
function inputField(parent,key,path,value){const l=document.createElement('label');l.className='form-field';const s=document.createElement('span');s.textContent=label(key);const multiline=['intro','headline','description','detail','contact'].includes(key)||String(value).length>100||path.includes('points');const el=document.createElement(multiline?'textarea':'input');if(!multiline)el.type='text';el.value=value;el.addEventListener('focus',checkpoint);el.addEventListener('input',()=>set(path,el.value));l.append(s,el);parent.append(l);}
function fields(parent,obj,path){for(const [key,value] of Object.entries(obj)){if(Array.isArray(value))arrayFields(parent,key,[...path,key]);else if(value!==null&&typeof value==='object')fields(parent,value,[...path,key]);else inputField(parent,key,[...path,key],value);}}
function arrayFields(parent,key,path){
 const box=document.createElement('div');if(path.length>1)box.className='array-nested';const h=document.createElement('h3');h.className='group-title';h.textContent=label(key);box.append(h);
 get(path).forEach((item,i)=>{const row=document.createElement('div');row.className='array-item';const top=document.createElement('div');top.className='array-top';const name=document.createElement('strong');name.textContent=(typeof item==='object'&&(item.role||item.title||item.degree||item.area||item.label))||label(key)+' '+(i+1);
 const controls=document.createElement('div');controls.className='row-controls';
 for(const [text,delta] of [['Move up',-1],['Move down',1]]){const b=button(text,()=>{checkpoint();const list=get(path);[list[i],list[i+delta]]=[list[i+delta],list[i]];save();renderForm();});b.disabled=i+delta<0||i+delta>=get(path).length;controls.append(b);}
 controls.append(button('Remove',()=>{checkpoint();get(path).splice(i,1);save();renderForm();}));top.append(name,controls);row.append(top);if(typeof item==='object')fields(row,item,[...path,i]);else inputField(row,'Text',[...path,i],item);box.append(row);});
 box.append(button('Add '+(key==='points'?'bullet':key==='links'?'link':'item'),()=>{checkpoint();get(path).push(templates[key]?structuredClone(templates[key]):'');save();renderForm();},'secondary add-item'));parent.append(box);
}
function renderForm(){const initial=!form.children.length;const openKeys=Array.from(form.querySelectorAll('details[open]')).map(e=>e.dataset.key);form.replaceChildren();function group(key){const d=document.createElement('details');d.dataset.key=key;d.open=initial?key==='identity':openKeys.includes(key);const s=document.createElement('summary');s.textContent=titles[key]||label(key);const c=document.createElement('div');c.className='group-content';d.append(s,c);form.append(d);return c;}const first=group('identity');identityKeys.forEach(k=>inputField(first,k,[k],profile[k]));['highlights','experience','projects','education','skills','elsewhere'].forEach(k=>arrayFields(group(k),k,[k]));inputField(group('contact'),'contact',['contact'],profile.contact);}
function download(blob,name){const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function sendPreview(){if(profile)frame.contentWindow.postMessage({type:'profile-preview',profile,assets:Object.fromEntries(Object.entries(assetURLs).filter(([kind])=>profile[kind]===assets[kind]?.path))},location.origin);}
$('preview-button').onclick=()=>{$('preview-area').hidden=false;sendPreview();$('preview-area').scrollIntoView({behavior:'smooth',block:'start'});};
window.addEventListener('message',e=>{if(e.origin===location.origin&&e.source===frame.contentWindow&&e.data?.type==='profile-ready')sendPreview();});
$('preview-width').onchange=e=>{frame.style.width=e.target.value;};
$('download-button').onclick=()=>{if(!profile)return;download(new Blob([JSON.stringify(profile,null,2)+'\n'],{type:'application/json'}),'profile.json');message('Downloaded profile.json. Upload it to the repository root and commit to main to publish. If you selected a new photo or CV, upload its replacement file to assets too.');};
$('undo-button').onclick=()=>{if(!history.length)return;profile=JSON.parse(history.pop());$('undo-button').disabled=!history.length;save();renderForm();};
async function loadPublished(){const r=await fetch('../profile.json',{cache:'no-store'});if(!r.ok)throw Error('Cannot load published profile');const d=await r.json();if(!validProfile(d))throw Error('Invalid profile format');return d;}
// Files remain local until explicitly downloaded and committed to GitHub.
let database;
function openDB(){if(database)return database;database=new Promise((resolve,reject)=>{const request=indexedDB.open('jamal-profile-assets',1);request.onupgradeneeded=()=>request.result.createObjectStore('files');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});return database;}
async function assetStore(mode,kind,value){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction('files',mode);const store=tx.objectStore('files');const req=value===undefined?store.get(kind):value===null?store.delete(kind):store.put(value,kind);tx.oncomplete=()=>resolve(req.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
function displayAsset(kind,asset){if(assetURLs[kind])URL.revokeObjectURL(assetURLs[kind]);if(asset){assets[kind]=asset;assetURLs[kind]=URL.createObjectURL(asset.file);$(kind+'-download').disabled=false;$(kind+'-status').textContent='Selected: '+asset.file.name+' → '+asset.path.split('/').pop();}else{delete assets[kind];delete assetURLs[kind];$(kind+'-download').disabled=true;$(kind+'-status').textContent='Using the published file.';$(kind+'-file').value='';}sendPreview();}
$('reset-button').onclick=async()=>{if(!profile||!confirm('Discard this browser draft and selected files, and reload the latest published profile?'))return;try{const latest=await loadPublished();for(const kind of ['photo','cv']){await assetStore('readwrite',kind,null).catch(()=>{});displayAsset(kind,null);}published=latest;profile=structuredClone(latest);history.length=0;$('undo-button').disabled=true;try{localStorage.removeItem(DRAFT);}catch(e){}renderForm();sendPreview();message('Latest published profile loaded. Local draft discarded; live content was not changed.');}catch(e){message('Could not reload published content. Your draft has been kept. Try again when you are online.');}};
$('import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2*1024*1024)throw Error('File too large');const d=JSON.parse(await f.text());if(!validProfile(d))throw Error('Invalid profile format');checkpoint();profile=d;save();renderForm();message('Imported profile.json into your local draft. Preview it, then download and commit to publish.');}catch(error){message('This is not a valid profile.json export. Your current draft was kept.');}e.target.value='';};
for(const kind of ['photo','cv']){
 const inp=$(kind+'-file'),btn=$(kind+'-download');
 inp.onchange=async()=>{const file=inp.files[0];if(!file||!profile)return;try{if(file.size>20*1024*1024)throw Error('Choose a file smaller than 20 MB.');const bytes=new Uint8Array(await file.slice(0,8).arrayBuffer());const pdf=String.fromCharCode(...bytes.slice(0,5))==='%PDF-';const png=[137,80,78,71,13,10,26,10].every((x,i)=>bytes[i]===x);const jpg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255;if(kind==='cv'?!pdf:!(jpg||png))throw Error(kind==='cv'?'Choose a valid PDF file.':'Choose a valid JPG or PNG file.');const name=kind==='cv'?'Jamal-Nasir-CV.pdf':png?'profile.png':'profile.jpg';const asset={file,path:'assets/'+name};checkpoint();profile[kind]=asset.path;displayAsset(kind,asset);save();renderForm();try{await assetStore('readwrite',kind,asset);message('File saved in this browser draft and ready to preview. Download the replacement file and profile.json, then upload both to GitHub.');}catch(e){message('File is ready to preview, but browser file storage is unavailable. Download it before closing this page.');}}catch(e){message(e.message);inp.value='';}};
 btn.onclick=()=>{const asset=assets[kind];if(!asset)return;download(asset.file,asset.path.split('/').pop());message('Downloaded '+asset.path.split('/').pop()+'. Upload this file to assets and profile.json to the repository root, then commit to publish.');};
}
(async()=>{try{published=await loadPublished();let draft=null;try{draft=JSON.parse(localStorage.getItem(DRAFT));}catch(e){}const restored=validProfile(draft);profile=structuredClone(restored?draft:published);renderForm();for(const id of ['preview-button','download-button','reset-button','import-file','photo-file','cv-file'])$(id).disabled=false;for(const kind of ['photo','cv']){try{const a=await assetStore('readonly',kind);if(a)displayAsset(kind,a);}catch(e){}}message(restored?'Loaded your saved browser draft. It is not published yet.':'Published content loaded. Edit a field to start a draft.');}catch(e){message('Could not load the profile. Your saved draft has not been deleted. Reload the page to retry.');}})();
