let profile,published;const DRAFT='jamal-profile-draft-v2';
const form=document.getElementById('editor-form'),status=document.getElementById('editor-status'),frame=document.getElementById('preview-frame');
const titles={identity:'Introduction & links',experience:'Work experience',projects:'Projects & portfolio',education:'Education',skills:'Skills & methods',elsewhere:'Other links',highlights:'Evidence & highlights',contact:'Contact message'};
const labelNames={cv:'CV file path',photo:'Photo file path',intro:'Introduction',current:'Current role',fields:'Subjects & sectors',points:'Experience bullets',methods:'Methods & tools',status:'Project status or year',url:'Link URL'};
const templates={experience:{role:'New role',organization:'',dates:'',fields:'',points:['']},projects:{title:'New project',category:'',description:'',methods:'',status:'',links:[]},education:{degree:'',institution:'',year:''},skills:{area:'',detail:''},elsewhere:{title:'',description:'',url:'https://'},links:{label:'',url:'https://'}};
const label=k=>labelNames[k]||k.replace(/_/g,' ').replace(/^./,s=>s.toUpperCase());
function get(path){return path.reduce((v,k)=>v[k],profile)}
function set(path,value){let v=profile;path.slice(0,-1).forEach(k=>v=v[k]);v[path.at(-1)]=value;save();}
function save(){try{localStorage.setItem(DRAFT,JSON.stringify(profile));status.textContent='Draft saved in this browser. Download and upload to GitHub to publish.';}catch(e){status.textContent='Browser storage unavailable. Download your changes before leaving this page.';}}
function button(text,fn,cls='secondary'){const b=document.createElement('button');b.type='button';b.textContent=text;b.className=cls;b.onclick=fn;return b;}
function inputField(parent,key,path,value){const l=document.createElement('label');l.className='form-field';const s=document.createElement('span');s.textContent=label(key);const multiline=['intro','headline','description','detail','contact'].includes(key)||String(value).length>100||path.includes('points');const el=document.createElement(multiline?'textarea':'input');if(!multiline)el.type='text';el.value=value;el.addEventListener('input',()=>set(path,el.value));l.append(s,el);parent.append(l);}
function fields(parent,obj,path){for(const [key,value] of Object.entries(obj)){if(Array.isArray(value))arrayFields(parent,key,[...path,key]);else if(value!==null&&typeof value==='object')fields(parent,value,[...path,key]);else inputField(parent,key,[...path,key],value);}}
function arrayFields(parent,key,path){const box=document.createElement('div');if(path.length>1)box.className='array-nested';const h=document.createElement('h3');h.className='group-title';h.textContent=label(key);box.append(h);get(path).forEach((item,i)=>{const row=document.createElement('div');row.className='array-item';const top=document.createElement('div');top.className='array-top';const name=document.createElement('strong');name.textContent=(typeof item==='object'&&(item.role||item.title||item.degree||item.area||item.label))||label(key)+' '+(i+1);top.append(name,button('Remove',()=>{get(path).splice(i,1);save();renderForm();}));row.append(top);if(typeof item==='object')fields(row,item,[...path,i]);else inputField(row,'Text',[...path,i],item);box.append(row);});box.append(button('Add '+(key==='points'?'bullet':key==='links'?'link':'item'),()=>{get(path).push(templates[key]?structuredClone(templates[key]):'');save();renderForm();},'secondary add-item'));parent.append(box);}
function renderForm(){const openKeys=Array.from(form.querySelectorAll('details[open]')).map(e=>e.dataset.key);form.replaceChildren();const identityKeys=['name','headline','intro','current','photo','cv','email','linkedin','github','research'];function group(key){const d=document.createElement('details');d.dataset.key=key;d.open=openKeys.length?openKeys.includes(key):key==='identity';const s=document.createElement('summary');s.textContent=titles[key]||label(key);const c=document.createElement('div');c.className='group-content';d.append(s,c);form.append(d);return c;}const first=group('identity');identityKeys.forEach(k=>inputField(first,k,[k],profile[k]));['highlights','experience','projects','education','skills','elsewhere'].forEach(k=>arrayFields(group(k),k,[k]));inputField(group('contact'),'contact',['contact'],profile.contact);}
function download(blob,name){const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function sendPreview(){frame.contentWindow.postMessage({type:'profile-preview',profile},location.origin);}
document.getElementById('preview-button').onclick=()=>{document.getElementById('preview-area').hidden=false;sendPreview();document.getElementById('preview-area').scrollIntoView({behavior:'smooth',block:'start'});};
window.addEventListener('message',e=>{if(e.origin===location.origin&&e.source===frame.contentWindow&&e.data?.type==='profile-ready'&&profile)sendPreview();});
document.getElementById('preview-width').onchange=e=>{frame.style.width=e.target.value;};
document.getElementById('download-button').onclick=()=>{if(!profile)return;download(new Blob([JSON.stringify(profile,null,2)+'\n'],{type:'application/json'}),'profile.json');status.textContent='Downloaded profile.json. Upload it to the repository root and commit to main to make these changes live.';};
document.getElementById('reset-button').onclick=()=>{if(!published)return;if(confirm('Discard the local draft and reload the published profile?')){profile=structuredClone(published);localStorage.removeItem(DRAFT);renderForm();sendPreview();status.textContent='Published profile loaded. No live content was changed.';}};
for(const kind of ['photo','cv']){const inp=document.getElementById(kind+'-file'),btn=document.getElementById(kind+'-download');inp.onchange=()=>{btn.disabled=!inp.files.length;};btn.onclick=()=>{const file=inp.files[0];if(!file)return;const name=kind==='cv'?'Jamal-Nasir-CV.pdf':file.type==='image/png'?'profile.png':'profile.jpg';if(kind==='photo'){profile.photo='assets/'+name;save();renderForm();}download(file,name);status.textContent='Downloaded '+name+'. Use “Upload files to assets” to replace the live file.';};}
(async()=>{try{const r=await fetch('../profile.json',{cache:'no-store'});if(!r.ok)throw Error('Cannot load published profile');published=await r.json();const draft=localStorage.getItem(DRAFT);try{profile=draft?JSON.parse(draft):structuredClone(published);}catch(e){profile=structuredClone(published);}renderForm();status.textContent=draft?'Loaded your saved browser draft. It is not published yet.':'Published content loaded. Edit a field to start a draft.';}catch(e){status.textContent='Could not load the profile. Please reload the page.';}})();
